name: Review code
run-name: "${{ github.actor }} reviewing code 🚀"
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
        types:
            - opened
            - reopened
            - synchronize
            - labeled
            - unlabeled    
jobs:
    review:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20]
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{matrix.node-version}}
              uses: actions/setup-node@v4
              with:
                node-version: ${{matrix.node-version}}
                cache: 'npm'
            - run: npm ci
            - run: npm run build --if-present
            - run: rm -rf .next