name: Review code

on:
    push:
        branches:
            - main
            - "releases/**"
    pull_request:
        branches:
            - main
jobs:
    review:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20, 18, 16]
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{  matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                node-version: ${{  matrix.node-version }}
                cache: 'npm'
            - run: npm ci
            - run: npm run build --if-present
            - run: npm test    